import type { ReservationJsonLd } from "@/lib/jsonld";
import type { CreateItineraryInput } from "@/lib/validation";

type EmailContent = {
  subject: string;
  html: string;
  text: string;
};

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function buildSummaryRows(input: CreateItineraryInput): Array<[string, string]> {
  if (input.kind === "flight") {
    return [
      ["Type", "Flight"],
      ["Reservation Number", input.reservationNumber],
      ["Passenger", input.passengerName],
      ["Airline", `${input.airlineName} (${input.airlineIataCode})`],
      ["Flight Number", input.flightNumber],
      [
        "Departure",
        `${input.departureAirportName} (${input.departureAirportIata}) at ${input.departureTimeIso}`,
      ],
      [
        "Arrival",
        `${input.arrivalAirportName} (${input.arrivalAirportIata}) at ${input.arrivalTimeIso}`,
      ],
    ];
  }

  return [
    ["Type", "Hotel"],
    ["Reservation Number", input.reservationNumber],
    ["Guest", input.guestName],
    ["Lodging", input.lodgingName],
    ["Phone", input.lodgingPhone],
    ["Check-in", input.checkinDateIso],
    ["Check-out", input.checkoutDateIso],
    [
      "Address",
      `${input.addressStreet}, ${input.addressLocality}, ${input.addressRegion}, ${input.addressPostalCode}, ${input.addressCountry}`,
    ],
  ];
}

export function renderConfirmationEmail(
  input: CreateItineraryInput,
  jsonLd: ReservationJsonLd
): EmailContent {
  const subjectPrefix = input.kind === "flight" ? "Flight" : "Hotel";
  const subject = `${subjectPrefix} reservation confirmation ${input.reservationNumber}`;

  const rows = buildSummaryRows(input)
    .map(
      ([label, value]) =>
        `<tr><td style="padding:6px 10px;font-weight:600;vertical-align:top;">${escapeHtml(label)}</td><td style="padding:6px 10px;">${escapeHtml(value)}</td></tr>`
    )
    .join("");

  const jsonLdInline = JSON.stringify(jsonLd).replaceAll("<", "\\u003c");

  const html = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body style="font-family:Arial,sans-serif;color:#111;line-height:1.4;">
    <h1 style="font-size:20px;margin-bottom:8px;">Reservation Confirmation</h1>
    <p style="margin-top:0;">This message was generated by your private itinerary app.</p>
    <table style="border-collapse:collapse;border:1px solid #ddd;">${rows}</table>
    <script type="application/ld+json">${jsonLdInline}</script>
  </body>
</html>`;

  const text = buildSummaryRows(input)
    .map(([label, value]) => `${label}: ${value}`)
    .join("\n");

  return {
    subject,
    html,
    text,
  };
}
